-- Este seed não cria usuários nem credenciais.
--
-- Crie o primeiro administrador pelo Supabase Auth/Dashboard ou por processo
-- operacional que receba credenciais fora do repositório. Depois, atribua o
-- papel em public.user_roles.
--
-- Nunca coloque senha, token ou service_role key neste arquivo.
