/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as StaffRouteRouteImport } from './routes/staff/route'
import { Route as SuperRouteRouteImport } from './routes/super/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAddOnsRouteImport } from './routes/admin/add-ons'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminDeliveryRouteImport } from './routes/admin/delivery'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffHistoryRouteImport } from './routes/staff/history'
import { Route as SuperIndexRouteImport } from './routes/super/index'
import { Route as SuperAvisosRouteImport } from './routes/super/avisos'
import { Route as SuperConfiguracoesRouteImport } from './routes/super/configuracoes'
import { Route as SuperDashboardRouteImport } from './routes/super/dashboard'
import { Route as SuperLogsRouteImport } from './routes/super/logs'
import { Route as SuperMonitoramentoRouteImport } from './routes/super/monitoramento'
import { Route as SuperPlanosRouteImport } from './routes/super/planos'
import { Route as SuperUsuariosRouteImport } from './routes/super/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperRouteRoute = SuperRouteRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAddOnsRoute = AdminAddOnsRouteImport.update({
  id: '/add-ons',
  path: '/add-ons',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffHistoryRoute = StaffHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => StaffRouteRoute,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperRouteRoute,
} as any)
const SuperAvisosRoute = SuperAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => SuperRouteRoute,
} as any)
const SuperConfiguracoesRoute = SuperConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => SuperRouteRoute,
} as any)
const SuperDashboardRoute = SuperDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SuperRouteRoute,
} as any)
const SuperLogsRoute = SuperLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => SuperRouteRoute,
} as any)
const SuperMonitoramentoRoute = SuperMonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => SuperRouteRoute,
} as any)
const SuperPlanosRoute = SuperPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => SuperRouteRoute,
} as any)
const SuperUsuariosRoute = SuperUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => SuperRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/super': typeof SuperRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin/add-ons': typeof AdminAddOnsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/staff/history': typeof StaffHistoryRoute
  '/super/avisos': typeof SuperAvisosRoute
  '/super/configuracoes': typeof SuperConfiguracoesRoute
  '/super/dashboard': typeof SuperDashboardRoute
  '/super/logs': typeof SuperLogsRoute
  '/super/monitoramento': typeof SuperMonitoramentoRoute
  '/super/planos': typeof SuperPlanosRoute
  '/super/usuarios': typeof SuperUsuariosRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/super/': typeof SuperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin/add-ons': typeof AdminAddOnsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/staff/history': typeof StaffHistoryRoute
  '/super/avisos': typeof SuperAvisosRoute
  '/super/configuracoes': typeof SuperConfiguracoesRoute
  '/super/dashboard': typeof SuperDashboardRoute
  '/super/logs': typeof SuperLogsRoute
  '/super/monitoramento': typeof SuperMonitoramentoRoute
  '/super/planos': typeof SuperPlanosRoute
  '/super/usuarios': typeof SuperUsuariosRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
  '/super': typeof SuperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/super': typeof SuperRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin/add-ons': typeof AdminAddOnsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/staff/history': typeof StaffHistoryRoute
  '/super/avisos': typeof SuperAvisosRoute
  '/super/configuracoes': typeof SuperConfiguracoesRoute
  '/super/dashboard': typeof SuperDashboardRoute
  '/super/logs': typeof SuperLogsRoute
  '/super/monitoramento': typeof SuperMonitoramentoRoute
  '/super/planos': typeof SuperPlanosRoute
  '/super/usuarios': typeof SuperUsuariosRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/super/': typeof SuperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/staff'
    | '/super'
    | '/$slug'
    | '/auth'
    | '/admin/add-ons'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/delivery'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/auth/reset-password'
    | '/staff/history'
    | '/super/avisos'
    | '/super/configuracoes'
    | '/super/dashboard'
    | '/super/logs'
    | '/super/monitoramento'
    | '/super/planos'
    | '/super/usuarios'
    | '/admin/'
    | '/staff/'
    | '/super/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/auth'
    | '/admin/add-ons'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/delivery'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/auth/reset-password'
    | '/staff/history'
    | '/super/avisos'
    | '/super/configuracoes'
    | '/super/dashboard'
    | '/super/logs'
    | '/super/monitoramento'
    | '/super/planos'
    | '/super/usuarios'
    | '/admin'
    | '/staff'
    | '/super'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/staff'
    | '/super'
    | '/$slug'
    | '/auth'
    | '/admin/add-ons'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/delivery'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/auth/reset-password'
    | '/staff/history'
    | '/super/avisos'
    | '/super/configuracoes'
    | '/super/dashboard'
    | '/super/logs'
    | '/super/monitoramento'
    | '/super/planos'
    | '/super/usuarios'
    | '/admin/'
    | '/staff/'
    | '/super/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  StaffRouteRoute: typeof StaffRouteRouteWithChildren
  SuperRouteRoute: typeof SuperRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/add-ons': {
      id: '/admin/add-ons'
      path: '/add-ons'
      fullPath: '/admin/add-ons'
      preLoaderRoute: typeof AdminAddOnsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/history': {
      id: '/staff/history'
      path: '/history'
      fullPath: '/staff/history'
      preLoaderRoute: typeof StaffHistoryRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/super/': {
      id: '/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof SuperRouteRoute
    }
    '/super/avisos': {
      id: '/super/avisos'
      path: '/avisos'
      fullPath: '/super/avisos'
      preLoaderRoute: typeof SuperAvisosRouteImport
      parentRoute: typeof SuperRouteRoute
    }
    '/super/configuracoes': {
      id: '/super/configuracoes'
      path: '/configuracoes'
      fullPath: '/super/configuracoes'
      preLoaderRoute: typeof SuperConfiguracoesRouteImport
      parentRoute: typeof SuperRouteRoute
    }
    '/super/dashboard': {
      id: '/super/dashboard'
      path: '/dashboard'
      fullPath: '/super/dashboard'
      preLoaderRoute: typeof SuperDashboardRouteImport
      parentRoute: typeof SuperRouteRoute
    }
    '/super/logs': {
      id: '/super/logs'
      path: '/logs'
      fullPath: '/super/logs'
      preLoaderRoute: typeof SuperLogsRouteImport
      parentRoute: typeof SuperRouteRoute
    }
    '/super/monitoramento': {
      id: '/super/monitoramento'
      path: '/monitoramento'
      fullPath: '/super/monitoramento'
      preLoaderRoute: typeof SuperMonitoramentoRouteImport
      parentRoute: typeof SuperRouteRoute
    }
    '/super/planos': {
      id: '/super/planos'
      path: '/planos'
      fullPath: '/super/planos'
      preLoaderRoute: typeof SuperPlanosRouteImport
      parentRoute: typeof SuperRouteRoute
    }
    '/super/usuarios': {
      id: '/super/usuarios'
      path: '/usuarios'
      fullPath: '/super/usuarios'
      preLoaderRoute: typeof SuperUsuariosRouteImport
      parentRoute: typeof SuperRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAddOnsRoute: typeof AdminAddOnsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAddOnsRoute: AdminAddOnsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface StaffRouteRouteChildren {
  StaffHistoryRoute: typeof StaffHistoryRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteRouteChildren: StaffRouteRouteChildren = {
  StaffHistoryRoute: StaffHistoryRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteRouteWithChildren = StaffRouteRoute._addFileChildren(
  StaffRouteRouteChildren,
)

interface SuperRouteRouteChildren {
  SuperAvisosRoute: typeof SuperAvisosRoute
  SuperConfiguracoesRoute: typeof SuperConfiguracoesRoute
  SuperDashboardRoute: typeof SuperDashboardRoute
  SuperLogsRoute: typeof SuperLogsRoute
  SuperMonitoramentoRoute: typeof SuperMonitoramentoRoute
  SuperPlanosRoute: typeof SuperPlanosRoute
  SuperUsuariosRoute: typeof SuperUsuariosRoute
  SuperIndexRoute: typeof SuperIndexRoute
}

const SuperRouteRouteChildren: SuperRouteRouteChildren = {
  SuperAvisosRoute: SuperAvisosRoute,
  SuperConfiguracoesRoute: SuperConfiguracoesRoute,
  SuperDashboardRoute: SuperDashboardRoute,
  SuperLogsRoute: SuperLogsRoute,
  SuperMonitoramentoRoute: SuperMonitoramentoRoute,
  SuperPlanosRoute: SuperPlanosRoute,
  SuperUsuariosRoute: SuperUsuariosRoute,
  SuperIndexRoute: SuperIndexRoute,
}

const SuperRouteRouteWithChildren = SuperRouteRoute._addFileChildren(
  SuperRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  StaffRouteRoute: StaffRouteRouteWithChildren,
  SuperRouteRoute: SuperRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
