// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isPublishableSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New publishable keys are opaque strings, not bearer JWTs.
    if (
      isPublishableSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export function createDummyClient(): SupabaseClient<Database> {
  const notConfigured = async () => ({ data: null, error: null });
  type QueryStub = {
    select: () => QueryStub;
    insert: () => QueryStub;
    update: () => QueryStub;
    delete: () => QueryStub;
    upsert: () => QueryStub;
    eq: () => QueryStub;
    neq: () => QueryStub;
    gt: () => QueryStub;
    gte: () => QueryStub;
    lt: () => QueryStub;
    lte: () => QueryStub;
    in: () => QueryStub;
    like: () => QueryStub;
    ilike: () => QueryStub;
    is: () => QueryStub;
    order: () => QueryStub;
    limit: () => QueryStub;
    range: () => QueryStub;
    single: typeof notConfigured;
    maybeSingle: typeof notConfigured;
    then: (resolve: (result: { data: never[]; error: null }) => unknown) => unknown;
  };

  const queryStub: QueryStub = {
    select: () => queryStub,
    insert: () => queryStub,
    update: () => queryStub,
    delete: () => queryStub,
    upsert: () => queryStub,
    eq: () => queryStub,
    neq: () => queryStub,
    gt: () => queryStub,
    gte: () => queryStub,
    lt: () => queryStub,
    lte: () => queryStub,
    in: () => queryStub,
    like: () => queryStub,
    ilike: () => queryStub,
    is: () => queryStub,
    order: () => queryStub,
    limit: () => queryStub,
    range: () => queryStub,
    single: notConfigured,
    maybeSingle: notConfigured,
    then: (resolve) => resolve({ data: [], error: null }),
  };
  return {
    from: () => queryStub,
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => ({ data: { user: null }, error: null }),
      getClaims: async () => ({ data: null, error: new Error("Supabase not configured") }),
      signInWithPassword: async () => ({
        data: null,
        error: new Error("Login local ainda não configurado."),
      }),
      signUp: async () => ({
        data: null,
        error: new Error("Cadastro local ainda não configurado."),
      }),
      signOut: async () => ({ error: null }),
      refreshSession: async () => ({ data: { session: null }, error: null }),
      resetPasswordForEmail: async () => ({
        data: null,
        error: new Error("Recuperação de senha ainda não configurada."),
      }),
      updateUser: async () => ({
        data: { user: null },
        error: new Error("Recuperação de senha ainda não configurada."),
      }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
    },
    channel: () => ({ on: () => ({ subscribe: () => ({}) }), subscribe: () => ({}) }),
    removeChannel: () => {},
  } as unknown as SupabaseClient<Database>;
}

function createSupabaseClient(): SupabaseClient<Database> {
  const SUPABASE_URL = import.meta.env["VITE_SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const message =
      "[Supabase] VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY são obrigatórias.";
    if (import.meta.env.PROD) throw new Error(message);
    if (typeof window !== "undefined") console.warn(message);
    return createDummyClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
